#100% {

opacity: 1;

}

}

</style>

</head>

<body>

<div class="message">

Happy Birthday Ananya Jii
!!ðŸ’<br> hamesa kush rhiye !!!

</div>

<div class="countdown">

<span id="years"></span> years, 

<span id="months"></span> months, 

<span id="days"></span> days, 

<span id="hours"></span> hours, 

<span id="minutes"></span> minutes, 

<span id="seconds"></span> seconds

</div>

<script>

const dob = new Date('2007-02-04T00:00:00'); // Ananya's date of birth

const birthdayMessage = document.querySelector('.message');

const countdownDisplay = {

years: document.getElementById('years'),

months: document.getElementById('months'),

days: document.getElementById('days'),

hours: document.getElementById('hours'),

minutes: document.getElementById('minutes'),

seconds: document.getElementById('seconds')

};

function updateCountdown() {

const now = new Date();

const ageInMilliseconds = now - dob;

const ageDate = new Date(ageInMilliseconds);

// Calculate time difference

const years = ageDate.getUTCFullYear() - 1970;

const months = ageDate.getUTCMonth();

const days = ageDate.getUTCDate() - 1;

const hours = now.getHours();

const minutes = now.getMinutes();

const seconds = now.getSeconds();

// Update the countdown display

countdownDisplay.years.textContent = years;

countdownDisplay.months.textContent = months;

countdownDisplay.days.textContent = days;

countdownDisplay.hours.textContent = hours;

countdownDisplay.minutes.textContent = minutes;

countdownDisplay.seconds.textContent = seconds;

}

setInterval(updateCountdown, 1000); // Update every second

updateCountdown(); // Initialize the countdown

</script>

</body>

</html>
 This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
